spring:
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true
  application:
    name: api-gateway
server:
  port: 18000
zuul:
  routes:
    main-data:
      path: /main-data/api/**
      serviceId: main-data
proxy:
  auth:
    routes:
      main-data: oauth2
security:
  ignored: |
    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,
    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers
  oauth2:
    resource:
      jwt:
        key-uri: http://${AUTH_CENTER_HOST:localhost}:${AUTH_CENTER_PORT:18001}/auth/oauth/token_key
      id: ${spring.application.name}
      serviceId: ${spring.application.name}
management:
  security:
    enabled: false