# 数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/main-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: fangp
      password: "000000"
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
  cloud:
      consul:
        host: 127.0.0.1
        port: 8500
        discovery:
          prefer-ip-address: true
  application:
      name: main-data
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
# 权限配置
security:
  ignored: |
    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,
    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,
    /user/name/**,/role/user/**,/menu/user/*
  oauth2:
    resource:
      jwt:
        key-uri: http://127.0.0.1:21001/auth/oauth/token_key
      id: ${spring.application.name}
      serviceId: ${spring.application.name}
# mybatis 配置
mybatis:
  type-aliases-package: com.peng.main.api.mapper.model
  mapper-locations: classpath:mybatis/mapper/*.xml
# mapper 配置
mapper:
  identity: select uuid()
  before: true
logging:
  file: logs/main-data.log
server:
  port: 21003