server:
  context-path: /auth
  port: 21001
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.context-path}/health
        tags: management.context-path=${server.context-path}
  application:
    name: auth-center
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/main-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: fangp
      password: "000000"
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
  freemarker:
      request-context-attribute: request
logging:
  file: logs/auth-center.log
management:
  security:
    enabled: false